In [1]:
import numpy as np

# =====================================================================
# Données d'exemple (Données d'essai)
# =====================================================================
# Matrice X (4 échantillons, 3 variables)
X = np.array([
    [2.5, 2.4, 0.5],
    [0.5, 0.7, 0.2],
    [2.2, 2.9, 0.9],
    [1.9, 2.2, 0.4]
])

K = 2  # Nombre de composantes principales à conserver

print("--- DONNÉES D'ORIGINE ---")
print("Taille de X :", X.shape)
print(X)
print("\n" + "="*50 + "\n")

--- DONNÉES D'ORIGINE ---
Taille de X : (4, 3)
[[2.5 2.4 0.5]
 [0.5 0.7 0.2]
 [2.2 2.9 0.9]
 [1.9 2.2 0.4]]




In [3]:
# Étape 1 : Standardiser les données
# =====================================================================
# 1.1 Calculer la moyenne de chaque variable (sur les colonnes)
mean = np.mean(X, axis=0)

# 1.2 Soustraire la moyenne de chaque valeur (Centrer)
X_centered = X - mean

# 1.3 Diviser par l'écart-type pour mettre à l'échelle (Réduire)
std = np.std(X, axis=0, ddof=1)
X_standardized = X_centered / std

print("ÉTAPE 1 : Standardisation")
print("Moyennes :", mean)
print("Écarts-types :", std)
print("Matrice standardisée :\n", X_standardized)
print("\n" + "="*50 + "\n")

ÉTAPE 1 : Standardisation
Moyennes : [1.775 2.05  0.5  ]
Écarts-types : [0.8845903  0.94692485 0.29439203]
Matrice standardisée :
 [[ 0.81958846  0.36961751  0.        ]
 [-1.44134522 -1.42566752 -1.01904933]
 [ 0.48044841  0.89764251  1.35873244]
 [ 0.14130835  0.1584075  -0.33968311]]




In [4]:
# Étape 2 : Calculer la matrice de covariance
# =====================================================================
# rowvar=False pour indiquer que les colonnes sont les variables
cov_matrix = np.cov(X_standardized, rowvar=False)

print("ÉTAPE 2 : Matrice de covariance")
print(cov_matrix)
print("\n" + "="*50 + "\n")

ÉTAPE 2 : Matrice de covariance
[[1.         0.93715617 0.69120088]
 [0.93715617 1.         0.87289106]
 [0.69120088 0.87289106 1.        ]]




In [5]:
# Étape 3 : Calculer les valeurs propres et les vecteurs propres
# =====================================================================
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("ÉTAPE 3 : Valeurs propres et Vecteurs propres")
print("Valeurs propres (Eigenvalues, Lambda) :\n", eigenvalues)
print("\nVecteurs propres (Eigenvectors) en colonnes :\n", eigenvectors)
print("\n" + "="*50 + "\n")

ÉTAPE 3 : Valeurs propres et Vecteurs propres
Valeurs propres (Eigenvalues, Lambda) :
 [2.67165927 0.31291718 0.01542355]

Vecteurs propres (Eigenvectors) en colonnes :
 [[-0.56956379 -0.6427056   0.5123735 ]
 [-0.60807907 -0.08993665 -0.78876564]
 [-0.55302525  0.76081595  0.33959117]]




In [6]:
# Étape 4 : Trier et sélectionner les K composantes
# =====================================================================
# Obtenir les indices triés par valeur propre décroissante
sorted_index = np.argsort(eigenvalues)[::-1]

# Réorganiser les valeurs et vecteurs propres
sorted_eigenvalues = eigenvalues[sorted_index]
sorted_eigenvectors = eigenvectors[:, sorted_index]

# Sélectionner les K premiers vecteurs propres
k_eigenvectors = sorted_eigenvectors[:, :K]

print("ÉTAPE 4 : Sélection des K composantes principales")
print("Valeurs propres triées :\n", sorted_eigenvalues)
print(f"\nLes {K} premiers vecteurs propres sélectionnés :\n", k_eigenvectors)
print("\n" + "="*50 + "\n")

ÉTAPE 4 : Sélection des K composantes principales
Valeurs propres triées :
 [2.67165927 0.31291718 0.01542355]

Les 2 premiers vecteurs propres sélectionnés :
 [[-0.56956379 -0.6427056 ]
 [-0.60807907 -0.08993665]
 [-0.55302525  0.76081595]]




In [7]:
# Étape 5 : Transformer le jeu de données
# =====================================================================
# Projection : Produit matriciel entre les données centré-réduites et les K vecteurs
X_projected = np.dot(X_standardized, k_eigenvectors)

print("ÉTAPE 5 : Données transformées (Dimension réduite)")
print("Nouvelle taille de la matrice :", X_projected.shape)
print("Résultat final :\n", X_projected)

ÉTAPE 5 : Données transformées (Dimension réduite)
Nouvelle taille de la matrice : (4, 2)
Résultat final :
 [[-0.69156458 -0.55999625]
 [ 2.25141665  0.27927141]
 [-1.57089699  0.64422748]
 [ 0.01104493 -0.36350264]]
